swagger: '2.0'
info:
  description: >-
    이 서버는 성균관대학교 2017년 봄학기 종합설계프로젝트 컴퓨터공학과     전용반 6조의 팀 프로젝트에서 사용되는 서버이다. 이
    프로젝트는 대학생     팀프로젝트 협업 툴에 관련되어 있다.
  version: 1.0.0
  title: Among
  termsOfService: 'http://among.iptime.org/'
  contact:
    email: hg9587@skku.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v2
tags:
  - name: user
    description: '회원가입, 회원탈퇴, 로그인, 로그아웃 등 유저와 관련된 항목들'
  - name: team
    description: '프로젝트 팀 생성, 삭제, 참여 등과 같은 프로젝트 팀과 관련된 항목들'
schemes:
  - http
paths: null
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Temporal_Schedule:
    type: object
    properties:
      name:
        type: string
      place:
        type: string
      title:
        type: string
      contents:
        type: string
      start_date:
        type: date
      end_date:
        type: date
  Regular_Schedule:
    type: object
    properties:
      name:
        type: string
      place:
        type: string
      title:
        type: string
      contents:
        type: string
      start_date:
        type: date
        description: 해당 일정이 적용되는 기간
      end_date:
        type: date
      start_time:
        type: time
        description: 해당 일정이 매주 수행되는 시간
      end_time:
        type: time
      day:
        type: string
        description: 해당 일정이 수행되는 요일
  Appointment_Schedule:
    type: object
    description: 팀에서 지정한 모임 일정
    properties:
      name:
        type: string
      place:
        type: string
      title:
        type: string
      contents:
        type: string
      team_id:
        type: string
      start_date:
        type: date
      end_date:
        type: date
  User:
    type: object
    properties:
      user_id:
        type: string
      name:
        type: string
      password:
        type: string
      schedule:
        type: array
        items:
          $ref: '#/definitions/Temporal_Schedule'
      team_id:
        type: array
  Invitation:
    type: object
    properties:
      team_id:
        type: string
      user_id:
        type: string
      state:
        enum: '-Accept -Reject -Pending'
  Team:
    type: object
    description: 팀의 프로젝트를 뜻한다
    properties:
      team_id:
        type: string
      name:
        type: string
      manager_id:
        type: string
      member_id:
        type: array
        description: array(user_id)
      contents:
        type: string
  File:
    type: object
    properties:
      file_directory:
        type: string
      file_name:
        type: string
      contents:
        type: string
        description: 일에 대한 간략한 설명
      uploader:
        type: user_id
      upload_time:
        type: date
  File_Manager:
    type: object
    description: Base64 Encoding 후 insert해도 됨
    properties:
      team_id:
        type: string
      file:
        type: object
        items:
          $ref: '#/definitions/File'
  Chat:
    type: object
    properties:
      team_id:
        type: string
      sender_id:
        type: string
      message_id:
        type: string
      time:
        type: date
  Chat_Data:
    type: object
    properties:
      message_id:
        type: string
      contents:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
